---
action: "drain"
target_hosts: []

nova_disable_reason: "maintenance: drained by ansible"

kubectl_drain_timeout: "30m"
kubectl_drain_extra_args:
  - "--ignore-daemonsets"
  - "--delete-emptydir-data"
  - "--force"

nova_poll_delay: 30
nova_poll_retries: 120

nova_delete_service_when_empty: false
taints_to_remove: []
run_on_localhost: true
openstack_cmd_timeout: 600
openstack_cloud: null

dry_run: true
exclude_amphora_from_migration: true

openstack_sdk_python: "python3"
openstack_sdk_requirements:
  - openstacksdk>=1.0.0
