---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
    image: docker.io/rockylinux/8:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
