---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: ../../..
      vars:
        action: drain
        target_hosts:
          - k8s_node: "fake-node"
            nova_compute_host: "fake-host"
        dry_run: true
